### ISSUE TITLE
Feature Request & Suggestion

### ISSUE THREAD

**Issue by mwsrc** [adunStudio/AdunDocs#1]
안녕하세요

인상깊은 프로젝트 보고 몇 가지 제안드리려고 이슈 열었습니다

https://github.com/gilbitron/Raneto 라는 오픈소스인데요.

이걸 기반으로 만들어진 사이트들 입니다. 
http://docs.raneto.com
http://attackerkb.com 

인터페이스로 고민 많이 하시는 것 같길래.. 한번 제안 드려봅니다.

대분류를 Raneto 처럼 하는 것도 보기 깔끔하고 괜찮다고 생각합니다.

**Comment by mwsrc** [comment]
## 맞춤법 검사 관련 기능

아톰 에디터 패키지로 되어 있는 예제가 있네요.

https://github.com/yomybaby/atom-korean-spell-daum

MIT 라이센스 따르고 있으니 활용하시면 맞춤법 검사도 가능할 것 같습니다.

**Comment by adunStudio** [comment]
### zer0worm 님 감사합니다.

맟춤법 검사기능은 잘 적용해보겠습니다.

 Raneto처럼 대분류를 해보자고 제안하는것은 메인에서 크게 하자는건가요?

**Comment by mwsrc** [comment]
@adunStudio 네 그건 메인에서 하시면 됩니다.

**Comment by mwsrc** [comment]
@adunStudio  나중에 또 생각나는 거 있으면 이슈에 써드릴 테니 가끔 확인해주세요. 이슈 이름도 "Feature Request & Suggestion"이니까 다른 분들도 기능 제안할 거 있으면 여기에 쓰거나 아마 새로 이슈를 여실 겁니다.

**Comment by adunStudio** [comment]
넵넵 관심가져주셔서 고마워요 ㅋㅋ

**Comment by mwsrc** [comment]
## 라이선스 관련

라이선스 관련 정보도 추가하시면 사람들이 더 많이 (마음 놓고) 사용할 수 있을 겁니다. 
관련 정보들은 아래 링크에서 확인하실 수 있습니다.
- [나무 위키](https://namu.wiki/w/%EC%98%A4%ED%94%88%20%EC%86%8C%EC%8A%A4)
- [OLIS](https://www.olis.or.kr/ossw/license/compareGuide.do)

감사합니다. 좋은 밤 되세요.

**Comment by zer0worm** [comment]
#Electron JS
일렉트론 JS를 활용해 아톰 같은 에디터로 만드는 것도 괜찮을 것 같아요.

- [ElectronJS](http://electron.atom.io/)
